###Current user
GET http://localhost:3000/auth/whoami
###Signout
POST http://localhost:3000/auth/signout
### create user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email":"marvel1@example.com",
    "password":"123456"
}
###Sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email":"marvel@example.com",
    "password":"123456"
}
### Get users by Email
GET http://localhost:3000/auth/users?email=example@gmail.com

### Get users by ID
GET http://localhost:3000/auth/2


### Update user
PATCH http://localhost:3000/auth/3
content-type: application/json

{
    "email":"example3@gmail.com"
}

### Delete user
DELETE http://localhost:3000/auth/1